name: CI

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/main.yml"
  pull_request:
    paths:
      - "**.py"

jobs:
  build-and-test:
    name: Run tests, linters and security checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: Install dependencies
        run: poetry install --no-root

      - name: Install type stubs
        run: |
          poetry run pip install types-passlib types-requests pandas-stubs

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Bandit
        run: poetry run bandit -r app/ --severity-level high

      - name: Run MyPy
        run: poetry run mypy app/

      - name: Run tests with coverage
        run: |
          poetry run pytest tests/unit --cov=app --cov-report=term-missing

  load-test:
    name: Run Locust load tests
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: Install dependencies
        run: poetry install --no-root

      - name: Start FastAPI server
        run: poetry run uvicorn app.fastapi_app:app --host 127.0.0.1 --port 8000 &

      - name: Wait for FastAPI to be ready
        run: |
          for i in {1..10}; do
            curl --fail http://127.0.0.1:8000/health && break
            sleep 1
          done

      - name: Run Locust load test
        run: poetry run locust -f tests/load/locustfile.py --headless --users 10 --spawn-rate 1 --run-time 1m --host http://127.0.0.1:8000

  fuzz-test:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run fuzz tests
        run: poetry run pytest tests/fuzz
