name: CI

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/main.yml"
  pull_request:
    paths:
      - "**.py"

jobs:
  build-and-test:
    name: Run tests, linters and security checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Bandit
        run: poetry run bandit -r app/ --severity-level high

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=app --cov-report=term-missing
